docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:

    - run:
        name: task0
        command: drush -y updb --cache-clear=0
        service: cli

    - run:
        name: task1
        command: drush -y cc all
        service: cli


cronjobs:
  - name: drush cron
    schedule: "*/15 * * * *"
    command: drush cron
    service: cli

environments:
  master:
    routes:
      - varnish:
        - "alt.wiche.edu":
            tls-acme: 'true'
            insecure: Redirect
