docker-compose-yaml: docker-compose.yml

tasks:


cronjobs:
  - name: drush cron
    schedule: "*/15 * * * *"
    command: drush cron
    service: cli

environments:
  master:
    routes:
      - varnish:
        - "alt.wiche.edu":
            tls-acme: 'true'
            insecure: Redirect
